default_platform(:android)

platform :android do
  desc "Lane For Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
      firebase_app_distribution(
    app: "1:230388692087:android:4afd6faf12b156f3c14272",
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    testers: "eliasmkh08@gmail.com",
    release_notes: "First Fastlane Firebase Distribution"

  )
  end
end

